- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2022111211092408580000000c.c97nxzgvmvn6.us-east-1.rds.amazonaws.com"
    login_user: "admin"
    login_password: "(Master##123)"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2022111211092408580000000c.c97nxzgvmvn6.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "admin" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "(Master##123)" }


