---
  - hosts: tag_Name_MC_Dev_ProxyServer_ASG
  - name: nginx assignment
    import_playbook: ../static-assignments/nginx.yml

  - hosts: tag_Name_MC_Dev_ToolingApp_LT
  - name: tooling assignment
    import_playbook: ../static-assignments/tooling.yml

  - hosts: tag_Name_MC_Dev_WordpressApp_LT
  - name: wordpress assignment
    import_playbook: ../static-assignments/wordpress.yml

  - hosts: tag_Name_MC_Dev_Jenkins_EC2
  - name: jenkins assignment
    import_playbook: ../static-assignments/jenkins.yml

  - hosts: tag_Name_MC_Dev_Artificatory_EC2
  - name: artifactory assignment
    import_playbook: ../static-assignments/jfrog.yml

  - hosts: tag_Name_MC_Dev_SonarQube_EC2
    user: ubuntu
  - name: sonarqube assignment
    import_playbook: ../static-assignments/sonar.yml





